### ISSUE TITLE
Resolve TODOs in db_config.pp

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckan-puppet-centos#17]

**Comment by BobTorgerson** [comment]
I don't think that we need to resolve those TODOs, as looking at the purpose of those TODOs, I purposefully set the database owners to the user ckan so that the Postgresql pg_hba.conf file could have the ckan user access the database using "ident" on localhost. I have also looked at the database and see that both databases that are created as part of the install are owned by the ckan user already. If you agree, I think we can delete the last section of the db_config.pp file, and close this issue.
