### ISSUE TITLE
Install Solr and have it run by Tomcat6

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/ckan-puppet-centos#2]
Puppet is currently downloading solr-4.9.1 into /tmp/ but need to have the code untar and move the directory structure into place for Tomcat to use. This is one of the last items that needs to be done for the CKAN install finished.

**Comment by BobTorgerson** [comment]
Similar to this information: http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#setup-solr

**Comment by brucecrevensten** [comment]
This is still ongoing/outstanding.  I got a more-or-less working install by manually following [these directions](https://github.com/ckan/ckan/wiki/How-To-Install-Apache-Solr-on-Red-Hat), and we can set it up to have a "multicore" just using a single core, [along these lines](http://docs.ckan.org/en/latest/maintaining/solr-multicore.html).  We still need to automate this provisioning in some fashion.

Since there's a number of shell commands that need to run in order to configure Solr correctly, it may make more sense to roll them up into a script and execute that as a single `exec` command in Puppet, [along these lines](https://ask.puppetlabs.com/question/10966/how-can-i-exec-a-script-stored-in-a-module/).

See the TODO items in the `solr.pp` file for some sketches that can accomplish this.
