### ISSUE TITLE
Update the metadata file to reflect correct info

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckan-puppet-centos#5]
located at: `puppet/modules/ckan`

**Comment by BobTorgerson** [comment]
Metadata.json file has been updated with correct information regarding our build. It is still a question whether or not we actually need the "maestrodev/wget" module, since it is only used in one location which appears unused. I will remove its use in my local build to confirm we can remove it as a dependency before I close this issue.

**Comment by BobTorgerson** [comment]
Modified the metadata file to no longer make use of the "maestrodev/wget" file as a dependency since we never make use of it in our builds.
